### ISSUE TITLE
Not working when using file:/// protocol

### ISSUE THREAD

**Issue by Pablo2048** [kuba2k2/firefox-webserial#14]
Hi,
at first I want to say big thank You for this plugin. I found strange behavior - when i open ie. `index.html`  directly from my computer folder (using file:/// protocol), I've got this error in console:
![image](https://github.com/user-attachments/assets/846bb9ac-c728-4107-a56c-7839a55e3c76)
When I run simple local web server (ie. `python -m http.server`), and open http://localhost:8000 with the same file everything is working correctly. It seems like the plugin code injection is not working when opening local file. Is this expected behavior or a bug?

**Comment by kuba2k2** [comment]
Extensions are not allowed to access the file:// protocol. This is a limitation of Firefox.

**Comment by Pablo2048** [comment]
Ok, so it is known feature - thank You for explanation...
