### ISSUE TITLE
Some serial ports are not shown in the list

### ISSUE THREAD

**Issue by anishsane** [kuba2k2/firefox-webserial#17]
I have 2 USB-serial devices connected to my windows 11 laptop.

```python.exe -c $'import serial.tools.list_ports as port_list\nfor p in port_list.comports(): print(hex(p.vid), p)'
0x10c4 COM10 - Silicon Labs CP210x USB to UART Bridge (COM10)
0x1a86 COM3 - USB-SERIAL CH340 (COM3)
```

On Chrome, I am able to see both the devices.
![image](https://github.com/user-attachments/assets/d835a1f4-b536-4883-9b81-bd57f414ef77)

However, on firefox, I can only see the COM3 device.
![image](https://github.com/user-attachments/assets/cb6b7a3c-a425-4175-b3f5-e7c88a165607)

I also tried changing the COM port number from COM10 to COM4. Did not help.
I am seeing similar behavior for the esp32 devkit module (which also uses the Silicon Labs CP210x chip).

I did not find any filtering logic for the devices in your code.

What could be the issue?
The 2 devices use 2 different drivers. But once it is visible to the OS, I guess, it should be transparent to webserial.
Am I missing some steps?

**Comment by kuba2k2** [comment]
Make sure the COM10 device is not used by Chrome - try closing that browser.

If that doesn't help, try capturing debug logs from the extension:
https://github.com/kuba2k2/firefox-webserial?tab=readme-ov-file#debugging

**Comment by anishsane** [comment]
I don't have any chrome process running.

Also, at the same time, I was able to connect to the COM10 port using python pyserial.
But it was not shown in the firefox list. (Of course, I closed the python process as well.)

```
08:57:15.622 / NATIVE <- TX(obj): 
{
  "action": "listPorts",
  "id": "93cbdeb4-da86-4963-a864-4f3a5a89c362"
}
```


```
08:57:15.663 / NATIVE -> RX(obj): 
{
  "id": "93cbdeb4-da86-4963-a864-4f3a5a89c362",
  "data": [
    {
      "id": "PCI\\VEN_8086&DEV_43E3&SUBSYS_0A5E1028&REV_11\\3&11583659&0&B3",
      "name": "COM256",
      "transport": "NATIVE",
      "description": "Intel(R) Active Management Technology - SOL (COM256)"
    },
    {
      "id": "USB\\VID_1A86&PID_7523\\B&D934611&0&4",
      "name": "COM5",
      "transport": "USB",
      "description": "USB-SERIAL CH340 (COM5)",
      "usb": {
        "bus": 1,
        "address": 44,
        "vid": 6790,
        "pid": 29987,
        "product": "USB2.0-Serial"
      }
    }
  ]
}
```

It appears that the native app firefox-webserial.exe is exposing only two devices and skipping COM10.

**Comment by kuba2k2** [comment]
Try connecting it to a different USB port/hub (2.0 vs 3.0, etc).

I have a CP2102 device and it is detected fine:

![obraz](https://github.com/user-attachments/assets/9557686f-cb22-492c-bfbd-f91278e5a958)

Apparently I'm still running v0.2.0 of the native program. If you want to try it, here's the installer (rename to .exe):
[firefox-webserial-v0.2.0.exe.rename.dmp](https://github.com/user-attachments/files/17935344/firefox-webserial-v0.2.0.exe.rename.dmp)

It's not on GitHub releases, because the build process crashed before it could upload the file.

That being said, it also works fine on v0.3.2:
![obraz](https://github.com/user-attachments/assets/d9dd4a96-42b1-47e8-bf0a-bcfeb02488f1)

**Comment by anishsane** [comment]
Still not showing up.

Mine is a USB 3.x / Thunderbolt port.
I also tried adding a USB 2.0 hub in between.

Probably need to add some debug prints in serial_list_ports_json.
I tried attaching windbg to the running firefox-webserial instance. But it is probably a release build, without debug info. So, I was not able to get any more details.

**Comment by kuba2k2** [comment]
There is nothing in serial_list_ports_json that can return an incomplete list of serial ports - if something goes wrong, nothing will be returned.

Looking at the underlying library `libserialport`, it uses Windows Registry to first query the list of available ports. Check the key `HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM` and see if your device is visible there.

**Comment by anishsane** [comment]
Thanks! This helped.
It was missing in the registry.
I tried adding a manual entry and it was visible in webserial.

Now I have to figure out why it is not getting auto-populated in the registry. (Other COM devices are getting auto-populated on adding/removing.)

In either case, it is not a firefox-webserial bug. Closing this issue.
Thanks again!

**Comment by kuba2k2** [comment]
Perhaps a better way of scanning for serial ports would be needed. I don't know why `libserialport` uses registry for that, of all things...
