### ISSUE TITLE
Support under Lnux

### ISSUE THREAD

**Issue by teras** [kuba2k2/firefox-webserial#2]
Hello.

Is there a technical reason why this is not supported under Linux? Maybe I can help somehow?

**Comment by kuba2k2** [comment]
Hi,
The main reason is that I don't normally use Linux and have limited ways to test that.
Additionally, Firefox on Windows uses registry to store the native application path. I don't know how it's done on Linux, I didn't find that in the docs.
If you know how to make Firefox launch the native app in Linux, it would probably compile and work just fine - the native application was written with platform compatibility in mind.

**Comment by teras** [comment]
OK let me investigate and I'll come back then :)

**Comment by kuba2k2** [comment]
Hi, the latest version 0.3.2 includes support for Linux, please update and try again :)
